[package]
name = "tfc-server"
description = "A server that facilitates remote control using the TFC library. Repo contains an iOS app."
keywords = ["keyboard", "mouse", "remote", "control"]
version = "0.7.0"
authors = ["Indiana Kernick <indiana.kernick@gmail.com>"]
edition = "2021"
repository = "https://github.com/indianakernick/The-Fat-Controller"
homepage = "https://github.com/indianakernick/The-Fat-Controller"
readme = "README.md"
categories = ["network-programming"]
license = "MIT OR Apache-2.0"

[dependencies]
tokio = { version = "1", features = ["rt", "sync", "macros"] }
tokio-tungstenite = "0"
futures = "0.3"
tfc = { version = "0.7", features = ["ascii-fallback", "tokio"], path = "../" }
openssl = "0.10"
qrcode = { version = "0.13", default-features = false }
base64 = { version = "0.21", default-features = false }

[profile.release]
lto = true
